package analytics

import (
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// GeneratePDF membuat PDF laporan kehadiran dan mengembalikan bytes-nya.
func GeneratePDF(
	summary *AttendanceSummary,
	deptStats []*DepartmentStat,
	topLate []*TopLateEmployee,
) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.AddPage()

	// ── Header ──────────────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 20)
	pdf.SetTextColor(37, 99, 235) // blue-600
	pdf.CellFormat(0, 10, "HADIR", "", 1, "C", false, 0, "")

	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(100, 116, 139) // slate-500
	pdf.CellFormat(0, 6, "Sistem Manajemen Kehadiran Karyawan", "", 1, "C", false, 0, "")

	pdf.Ln(3)
	pdf.SetDrawColor(226, 232, 240) // slate-200
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(4)

	// Periode laporan
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(15, 23, 42) // slate-900
	pdf.CellFormat(0, 7, "Laporan Kehadiran Karyawan", "", 1, "C", false, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(71, 85, 105) // slate-600
	pdf.CellFormat(0, 6,
		fmt.Sprintf("Periode: %s s/d %s", summary.PeriodStart, summary.PeriodEnd),
		"", 1, "C", false, 0, "")
	pdf.Ln(6)

	// ── Section 1: Ringkasan Eksekutif ──────────────────────────────────────
	sectionHeader(pdf, "1. Ringkasan Eksekutif")

	data := [][]string{
		{"Total Karyawan", fmt.Sprintf("%d orang", summary.TotalEmployees)},
		{"Total Hari Kerja Tercatat", fmt.Sprintf("%d hari", summary.TotalWorkingDays)},
		{"Total Hadir", fmt.Sprintf("%d hari", summary.TotalPresent)},
		{"Total Terlambat", fmt.Sprintf("%d hari", summary.TotalLate)},
		{"Total Alpha", fmt.Sprintf("%d hari", summary.TotalAbsent)},
		{"Total Izin", fmt.Sprintf("%d hari", summary.TotalLeave)},
		{"Total Sakit", fmt.Sprintf("%d hari", summary.TotalSick)},
		{"Tingkat Kehadiran", fmt.Sprintf("%.1f%%", summary.AttendanceRate)},
		{"Tingkat Keterlambatan", fmt.Sprintf("%.1f%%", summary.LatenessRate)},
	}

	for i, row := range data {
		if i%2 == 0 {
			pdf.SetFillColor(248, 250, 252) // slate-50
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(51, 65, 85)
		pdf.CellFormat(80, 7, row[0], "1", 0, "L", true, 0, "")
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(100, 7, row[1], "1", 1, "L", true, 0, "")
	}
	pdf.Ln(6)

	// ── Section 2: Statistik Per Departemen ─────────────────────────────────
	sectionHeader(pdf, "2. Statistik Per Departemen")

	// Header tabel
	tableHeader(pdf, []string{"Departemen", "Karyawan", "Hadir", "Terlambat", "Alpha", "% Hadir"},
		[]float64{60, 25, 25, 25, 25, 20})

	for i, d := range deptStats {
		if i%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(51, 65, 85)
		pdf.CellFormat(60, 6, d.Department, "1", 0, "L", true, 0, "")
		pdf.CellFormat(25, 6, fmt.Sprintf("%d", d.TotalEmployees), "1", 0, "C", true, 0, "")
		pdf.CellFormat(25, 6, fmt.Sprintf("%d", d.TotalPresent), "1", 0, "C", true, 0, "")
		pdf.CellFormat(25, 6, fmt.Sprintf("%d", d.TotalLate), "1", 0, "C", true, 0, "")
		pdf.CellFormat(25, 6, fmt.Sprintf("%d", d.TotalAbsent), "1", 0, "C", true, 0, "")
		pdf.CellFormat(20, 6, fmt.Sprintf("%.1f%%", d.AttendanceRate), "1", 1, "C", true, 0, "")
	}
	pdf.Ln(6)

	// ── Section 3: Top Karyawan Terlambat ───────────────────────────────────
	if len(topLate) > 0 {
		sectionHeader(pdf, "3. Top 10 Karyawan Paling Sering Terlambat")

		tableHeader(pdf, []string{"Nama Karyawan", "Departemen", "Terlambat", "Alpha"},
			[]float64{70, 60, 30, 20})

		for i, e := range topLate {
			if i%2 == 0 {
				pdf.SetFillColor(248, 250, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			pdf.SetFont("Helvetica", "", 9)
			pdf.SetTextColor(51, 65, 85)
			pdf.CellFormat(70, 6, e.Name, "1", 0, "L", true, 0, "")
			pdf.CellFormat(60, 6, e.Department, "1", 0, "L", true, 0, "")
			pdf.CellFormat(30, 6, fmt.Sprintf("%d kali", e.LateCount), "1", 0, "C", true, 0, "")
			pdf.CellFormat(20, 6, fmt.Sprintf("%d", e.AbsentCount), "1", 1, "C", true, 0, "")
		}
		pdf.Ln(6)
	}

	// ── Footer ──────────────────────────────────────────────────────────────
	pdf.SetY(-20)
	pdf.SetDrawColor(226, 232, 240)
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(2)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(148, 163, 184) // slate-400
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by Hadir — %s", time.Now().Format("02 January 2006, 15:04 WIB")),
		"", 0, "C", false, 0, "")

	// Output ke bytes
	var buf []byte
	err := pdf.Output((*byteWriter)(&buf))
	if err != nil {
		return nil, fmt.Errorf("output PDF: %w", err)
	}

	return buf, nil
}

// sectionHeader menulis judul section dengan styling.
func sectionHeader(pdf *gofpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetTextColor(37, 99, 235)
	pdf.SetFillColor(239, 246, 255) // blue-50
	pdf.CellFormat(0, 8, "  "+title, "LTB", 1, "L", true, 0, "")
	pdf.Ln(2)
}

// tableHeader menulis header tabel dengan background biru.
func tableHeader(pdf *gofpdf.Fpdf, headers []string, widths []float64) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFillColor(37, 99, 235) // blue-600
	for i, h := range headers {
		pdf.CellFormat(widths[i], 7, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)
}

// byteWriter adalah io.Writer yang mengumpulkan bytes ke slice.
type byteWriter []byte

func (b *byteWriter) Write(p []byte) (n int, err error) {
	*b = append(*b, p...)
	return len(p), nil
}
