server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip basic
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript application/xml image/svg+xml;
    gzip_min_length 1024;

    # Long-cache for hashed assets produced by Vite
    location /_app/ {
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # Proxy API ke backend Go
    location /api/ {
        proxy_pass         http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  $scheme;
        proxy_read_timeout 90s;
    }

    # Serve uploaded files via backend
    location /uploads/ {
        proxy_pass         http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
    }

    # SPA fallback — adapter-static menghasilkan index.html sebagai fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
